# Generated by Django 4.0.1 on 2022-01-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Phone_number', models.IntegerField()),
                ('Date_of_birth', models.DateField()),
                ('Document', models.CharField(choices=[('AC', 'Aadhar card'), ('PC', 'Pan card')], default='AC', max_length=11)),
                ('document_no', models.CharField(default=0, max_length=15)),
                ('Verified', models.BooleanField()),
            ],
        ),
    ]
