# Generated by Django 4.0.1 on 2022-01-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='document_no',
            field=models.CharField(max_length=15),
        ),
    ]
