# Generated by Django 4.0.1 on 2022-02-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_registrations_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrations',
            old_name='uuid',
            new_name='uid',
        ),
    ]
