# Generated by Django 4.0.1 on 2022-02-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_uuid_registrations_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
    ]
