# Generated by Django 4.0.1 on 2022-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_registrations_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='Password',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
