# Generated by Django 4.0.1 on 2022-02-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_registrations_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
