# Generated by Django 4.0.1 on 2022-02-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_registrations_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='logged_in',
        ),
    ]
