# Generated by Django 4.0.1 on 2022-02-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_registrations_logged_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrations',
            old_name='users',
            new_name='device1',
        ),
        migrations.AddField(
            model_name='registrations',
            name='device2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrations',
            name='device3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
