# Generated by Django 4.0.1 on 2024-09-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_users_registrations_device1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='Password',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
